"""ajout colonne archived

Revision ID: 72705f951d9c
Revises: 15b2d22b9902
Create Date: 2026-01-15 21:17:39.941722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72705f951d9c'
down_revision: Union[str, Sequence[str], None] = '15b2d22b9902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'archived')
    # ### end Alembic commands ###
