"""ajout de la colonne diagnostic

Revision ID: 89b3ed62e618
Revises: e637b4eaa2de
Create Date: 2026-01-18 16:51:09.709546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b3ed62e618'
down_revision: Union[str, Sequence[str], None] = 'e637b4eaa2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
