"""ajout de la colonne diagnostic

Revision ID: b560e8eb7618
Revises: 89b3ed62e618
Create Date: 2026-01-18 16:52:27.814469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b560e8eb7618'
down_revision: Union[str, Sequence[str], None] = '89b3ed62e618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('diagnostic', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'diagnostic')
    # ### end Alembic commands ###
