"""add_similarity_score_to_association_tables

Revision ID: b69dcf0773e8
Revises: d52bfec0df79
Create Date: 2026-01-21 14:46:58.467331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b69dcf0773e8"
down_revision: Union[str, Sequence[str], None] = "d52bfec0df79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents_proches", sa.Column("similarity_score", sa.Float(), nullable=True)
    )
    op.add_column(
        "patients_proches", sa.Column("similarity_score", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients_proches", "similarity_score")
    op.drop_column("documents_proches", "similarity_score")
    # ### end Alembic commands ###
