"""add_patients_proches_and_documents_proches_relations

Revision ID: d52bfec0df79
Revises: 8d8067aec651
Create Date: 2026-01-21 13:11:38.538650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d52bfec0df79"
down_revision: Union[str, Sequence[str], None] = "8d8067aec651"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents_proches",
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("patient_id", "document_id"),
    )
    op.create_table(
        "patients_proches",
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("patient_proche_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_proche_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("patient_id", "patient_proche_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("patients_proches")
    op.drop_table("documents_proches")
    # ### end Alembic commands ###
