"""Adding 'contexte' field for patients

Revision ID: e637b4eaa2de
Revises: 72705f951d9c
Create Date: 2026-01-16 09:52:05.038487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e637b4eaa2de"
down_revision: Union[str, Sequence[str], None] = "72705f951d9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patients", sa.Column("contexte", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patients", "contexte")
    # ### end Alembic commands ###
